# Generated by Django 5.1.4 on 2024-12-20 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_artist_alter_song_song_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Style',
        ),
    ]
