# Generated by Django 5.1.4 on 2024-12-20 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_artist_options_alter_style_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='category',
            new_name='style',
        ),
    ]
