# Generated by Django 5.1.4 on 2024-12-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_category_song_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='show',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='style',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
