# Generated by Django 5.1.4 on 2024-12-20 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_artist_show_style_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='Songs/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='tab',
            field=models.FileField(blank=True, upload_to='Tabs/'),
        ),
    ]
