# Generated by Django 5.1.4 on 2024-12-22 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_song_tab'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'verbose_name': 'Song', 'verbose_name_plural': 'Songs'},
        ),
    ]
