# Generated by Django 5.1.4 on 2024-12-22 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_song_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.artist'),
        ),
    ]
