# Generated by Django 5.1.4 on 2025-01-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_song_song_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='user',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='user',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
